language: python
sudo: required
dist: trusty

python:
  - '3.5'

matrix:
  fast_finish: true

branches:
 only:
 - master
 - devel
 - /^[0-9]+\.[0-9]+\.[0-9]+[.0-9ab]*$/

cache:
- pip: true
services:
- redis-server
- mongodb
- postgresql
addons:
  apt:
    packages:
    - swig
    - libzmq3-dev
    - libgmp-dev
    - libglpk-dev
    - glpk-utils
    - libopenbabel-dev
    - pandoc

before_install:
# download and install miniconda
- wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/conda
- export PATH="$HOME/conda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
# Useful for debugging any issues with conda
- conda info -a

# create and activate the build/test environment
- conda create -q -n tenv python=$TRAVIS_PYTHON_VERSION pip cmake
- source activate tenv

- pip install pip --upgrade
- pip install codecov

install:
# install rdkit from rdkit
- conda install -q -c rdkit boost rdkit=2016.09.4

- pip install flake8 cython numpy scipy pyzmq pandas pytest pytest-cov pytest-benchmark
- pip install .[test]
before_script:
- if [[ $TRAVIS_PYTHON_VERSION == "3.5" ]]; then flake8 marsi; fi
- gunzip tests/fixtures/marsi-db-sample.sql.gz
- psql -c 'create database marsi-db;' -U postgres
- pg_restore -d marsi-db -U postgres -h localhost tests/fixtures/marsi-db-sample.sql
script:
- python -c 'from rdkit import Chem'
- python -c 'import pybel'
- pytest -v -rsx --cov=marsi tests

after_success:
- codecov

before_deploy:
  - cd docs
  - make apidoc
  - make html
  - touch _build/html/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/_build/html
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  target-branch: gh-pages
  on:
    branch: master
    repo: biosustain/marsi