environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"
    PIP_CACHE_DIR: "pip_cache"
    POSTGRES_PATH: C:\Program Files\PostgreSQL\9.4
    PGUSER: postgres
    PGPASSWORD: Password12!

  matrix:
    - PYTHON: "C:\\Miniconda-x64"
      PYTHON_VERSION: "2.7.12"
      PYTHON_ARCH: "64"
      CONDA: true

    - PYTHON: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "64"
      CONDA: true

    - PYTHON: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.6.0"
      PYTHON_ARCH: "64"
      CONDA: true

services:
  - postgresql94

clone_depth: 25

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%bit"

cache:
    - pip_cache -> appveyor.yml


install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%POSTGRES_PATH%\bin;%PATH%"
  - ps: |
    conda config --set always_yes yes --set changeps1 no;
    conda install -q pip
  - cmd: conda install -q -c rdkit rdkit
  - cmd: conda install -q -c openbabel openbabel"
  - cmd:  pip install pytest pytest-cov"
  - cmd:  pip install cython"
  - cmd: createdb marsi-db
  - cmd: marsi db migrate
  - cmd: python bin/restore_db.py"
  - cmd: psql -d marsi-db -c 'SELECT COUNT(*) FROM metabolites;' -U postgres

build: off

test_script:
  - pytest test